### Readings 

Full list of papers **read by** or of interest to the class this semester 

- Weeks 1 & 2: Gettings started and basic neuroscience
- Week 3: Perspective
    - **Krakauer, J. W., Ghazanfar, A. A., Gomez-Marin, A., MacIver, M. A., & Poeppel, D. (2017). Neuroscience needs behavior: correcting a reductionist bias. Neuron, 93(3), 480-490.**
    - **Embick, D., & Poeppel, D. (2015). Towards a computational (ist) neurobiology of language: correlational, integrated and explanatory neurolinguistics. Language, cognition and neuroscience, 30(4), 357-366.**
    - Poeppel, D., & Adolfi, F. (2020). Against the epistemological primacy of the hardware: The brain from inside out, turned upside down. Eneuro, 7(4).
- Week 4: Networks
    - **Malik-Moraleda, S., Ayyash, D., Gallée, J., Affourtit, J., Hoffmann, M., Mineroff, Z., ... & Fedorenko, E. (2022). An investigation across 45 languages and 12 language families reveals a universal language network. Nature Neuroscience, 25(8), 1014-1019.**
    - **Fedorenko, E., Ivanova, A. A., & Regev, T. I. (2024). The language network as a natural kind within the broader landscape of the human brain. Nature Reviews Neuroscience, 1-24.**
    - Fedorenko, E., & Thompson-Schill, S. L. (2014). Reworking the language network. Trends in cognitive sciences, 18(3), 120-126.
    - Friederici, A. D., & Gierhan, S. M. (2013). The language network. Current opinion in neurobiology, 23(2), 250-254.
- Week 5: Phonemes, Syntax, Semantics (3)
    - Brodbeck, C., Hong, L. E., & Simon, J. Z. (2018). Rapid transformation from auditory to linguistic representations of continuous speech. Current Biology, 28(24), 3976-3983.
    - Ding, N., Melloni, L., Zhang, H., Tian, X., & Poeppel, D. (2016). Cortical tracking of hierarchical linguistic structures in connected speech. Nature neuroscience, 19(1), 158-164.
    - Scott, S. K., Blank, C. C., Rosen, S., & Wise, R. J. (2000). Identification of a pathway for intelligible speech in the left temporal lobe. Brain, 123(12), 2400-2406.
    - **Fitch, W. T., & Martins, M. D. (2014). [Hierarchical processing in music, language, and action: Lashley revisited. Annals of the New York Academy of Sciences](/assests/readings/fitch-martins-2014.pdf), 1316(1), 87-104.**
    - Lau, E. F., Phillips, C., & Poeppel, D. (2008). A cortical network for semantics:(de) constructing the N400. Nature reviews neuroscience, 9(12), 920-933.
    - **Makuuchi, M., Bahlmann, J., Anwander, A., & Friederici, A. D. (2009). [Segregating the core computational faculty of human language from working memory. Proceedings of the National Academy of Sciences](/assests/readings/makuuchi-et-al-2009.pdf), 106(20), 8362-8367.**
    - Kaan, E., & Swaab, T. Y. (2002). The brain circuitry of syntactic comprehension. Trends in cognitive sciences, 6(8), 350-356.
- Week 6: No class, fall break
- Week 7: Acquisition 1 (3)
    - Catani, M., Jones, D. K., & Ffytche, D. H. (2005). Perisylvian language networks of the human brain. Annals of Neurology: Official Journal of the American Neurological Association and the Child Neurology Society, 57(1), 8-16.
    - **Perani, D., Saccuman, M. C., Scifo, P., Anwander, A., Spada, D., Baldoli, C., ... & Friederici, A. D. (2011). [Neural language networks at birth](https://paperpile.com/shared/sMA8ZGuk1SPKvzFN6USIk6g). Proceedings of the National Academy of Sciences, 108(38), 16056-16061.**
    - **Leroy, F., Glasel, H., Dubois, J., Hertz-Pannier, L., Thirion, B., Mangin, J. F., & Dehaene-Lambertz, G. (2011). [Early maturation of the linguistic dorsal pathway in human infants](https://paperpile.com/shared/sbuQsks96Q7y6iBI_lpY3PQ). Journal of Neuroscience, 31(4), 1500-1506.**
    - **Skeide, M. A., & Friederici, A. D. (2016). [The ontogeny of the cortical language network](https://paperpile.com/shared/sc~PeRO27SR6PWvaIkGbl~w). Nature Reviews. Neuroscience, 17(5), 323–332.**
- Week 8: No class, Katie @ conference
- Week 9: Acquisition 2 (3)
    - **Cheng, Q., Roth, A., Halgren, E., Klein, D., Chen, J.-K., & Mayberry, R. I. (2023). [Restricted language access during childhood affects adult brain structure in selective language regions](https://paperpile.com/shared/sB1uCvQbrRx21mbYw77OkuQ). Proceedings of the National Academy of Sciences of the United States of America, 120(7), e2215423120.**
    - **Schipke, C. S., Knoll, L. J., Friederici, A. D., & Oberecker, R. (2012). [Preschool children’s interpretation of object-initial sentences: neural correlates of their behavioral performance: Children’s interpretation of object-initial sentences.](https://paperpile.com/shared/sjO_4tcsDRp~9Q3P_7Ej0xA) Developmental Science, 15(6), 762–774.**
    - **Petitto, L. A., Berens, M. S., Kovelman, I., Dubins, M. H., Jasinska, K., & Shalinsky, M. (2012). [The “Perceptual Wedge Hypothesis” as the basis for bilingual babies’ phonetic processing advantage: new insights from fNIRS brain imaging.](https://paperpile.com/shared/sXy5lgxSRTv2Xww1D_z9PzA) Brain and Language, 121(2), 130–143.**

    -  Werker, J. F., & Hensch, T. K. (2015). Critical periods in speech perception: new directions. Annual review of psychology, 66(1), 173-196.
    - Martin, K. C., Seydell-Greenwald, A., Berl, M. M., Gaillard, W. D., Turkeltaub, P. E., & Newport, E. L. (2022). A weak shadow of early life language processing persists in the right hemisphere of the mature brain. Neurobiology of Language (Cambridge, Mass.), 3(3), 364–385.
    - Friedrich, M., & Friederici, A. D. (2005). Phonotactic knowledge and lexical-semantic processing in one-year-olds: Brain responses to words and nonsense words in picture contexts. Journal of Cognitive Neuroscience, 17(11), 1785-1802.
    - Lenneberg, E. H. (1969). On Explaining Language: The development of language in children can best be understood in the context of developmental biology. Science, 164(3880), 635-643.
- Week 10: Bilingualism 1 (3)
    - **[Kim, K. H. S., Relkin, N. R., Lee, K.-M., & Hirsch, J. (1997). Distinct cortical areas associated with native and second languages. Nature, 388(6638), 171–174.](https://paperpile.com/shared/sWOkFczB6RBWf8PRruWsuXg)**
    - [Pierce, L. J., Klein, D., Chen, J. K., Delcenserie, A., & Genesee, F. (2014). Mapping the unconscious maintenance of a lost first language. Proceedings of the National Academy of Sciences, 111(48), 17314-17319.](https://paperpile.com/shared/s5dXrw4_GTAC1O7VyfGRGTw)
    - **[Phillips, S. F., & Pylkkänen, L. (2021). Composition within and between languages in the bilingual mind: MEG evidence from Korean/English bilinguals. eNeuro, 8(6), ENEURO.0084-21.2021.](https://paperpile.com/shared/swBkiPMnWS2WKp6AuizPheA)**
    - Weber-Fox, C. M., & Neville, H. J. (1996). Maturational constraints on functional specializations for language processing: ERP and behavioral evidence in bilingual speakers. Journal of cognitive neuroscience, 8(3), 231-256.
- Week 11: No class, Katie @ conference
- Week 12: Bilingualism 2 (2)
    - [Pallier, C., Dehaene, S., Poline, J.-B., LeBihan, D., Argenti, A.-M., Dupoux, E., & Mehler, J. (2003). Brain imaging of language plasticity in adopted adults: can a second language replace the first? Cerebral Cortex (New York, N.Y.: 1991), 13(2), 155–161.](https://paperpile.com/shared/shS5TPdTURryke2ECX1wAEw)
    - [Osterhout, L., McLaughlin, J., Pitkänen, I., Frenck-Mestre, C., & Molinaro, N. (2006). Novice learners, longitudinal designs, and event‐related potentials: A means for exploring the neurocognition of second language processing: Novice learners, longitudinal designs, ERPs. Language Learning, 56(s1), 199–230.](https://paperpile.com/shared/sgTjezxGIRXWZ_OrG2iq3BQ)
    - [Bialystok, E., Craik, F. I. M., & Freedman, M. (2007). Bilingualism as a protection against the onset of symptoms of dementia. Neuropsychologia, 45(2), 459–464.](https://paperpile.com/shared/srBh_WoLBQ2WoR5ue_6wkpg)
- Week 13: Sign language (3) 
    - [Mayberry, R. I., Chen, J. K., Witcher, P., & Klein, D. (2011). Age of acquisition effects on the functional organization of language in the adult brain. Brain and language, 119(1), 16-29.](https://paperpile.com/shared/sI9YdcjjXQ52G_VkyIYXINg)
    - [Nishimura, H., Hashikawa, K., Doi, K., Iwaki, T., Watanabe, Y., Kusuoka, H., ... & Kubo, T. (1999). Sign language ‘heard’in the auditory cortex. Nature, 397(6715), 116-116.](https://paperpile.com/shared/sW2iczH2cSUKdoDObrMhpWg)
    - [Petitto, L. A., Zatorre, R. J., Gauna, K., Nikelski, E. J., Dostie, D., & Evans, A. C. (2000). Speech-like cerebral activity in profoundly deaf people processing signed languages: implications for the neural basis of human language. Proceedings of the National Academy of Sciences, 97(25), 13961-13966.](https://paperpile.com/shared/szUUCYuuFQ0ilgSGeAZMpMw)
- Week 14: No class, Thanksgiving break 
- Week 15: Evolution (2)
    - [Rilling, J. K., Glasser, M. F., Preuss, T. M., Ma, X., Zhao, T., Hu, X., & Behrens, T. E. (2008). The evolution of the arcuate fasciculus revealed with comparative DTI. Nature neuroscience, 11(4), 426-428.](https://paperpile.com/shared/sxFcFs3goS02b_ZUz4sItZg)
    - Fitch, W. T. (2018). The biology and evolution of speech: a comparative analysis. Annual review of linguistics, 4(1), 255-279.**
    - Fisher, S. E., & Scharff, C. (2009). FOXP2 as a molecular window into speech and language. Trends in Genetics, 25(4), 166-177.
    - Wilson, B., Marslen-Wilson, W. D., & Petkov, C. I. (2017). Conserved sequence processing in primate frontal cortex. Trends in neurosciences, 40(2), 72-82.
    - [Sakai, T., Mikami, A., Tomonaga, M., Matsui, M., Suzuki, J., Hamada, Y., Tanaka, M., Miyabe-Nishiwaki, T., Makishima, H., Nakatsukasa, M., & Matsuzawa, T. (2011). Differential prefrontal white matter development in chimpanzees and humans. Current Biology: CB, 21(16), 1397–1402.](https://paperpile.com/shared/sF5DZ4ELXRNSDh5oWw4gu~Q)
    - [Bolhuis, J. J., & Moorman, S. (2015). Birdsong memory and the brain: in search of the template. Neuroscience and Biobehavioral Reviews, 50, 41–55.](https://paperpile.com/shared/s27HrrjAARM2o6aGrV9sSPg)
- Week 16: No class, reading period 
- Not covered this year: Cerebellum
    - Lesage, E., Morgan, B. E., Olson, A. C., Meyer, A. S., & Miall, R. C. (2012). Cerebellar rTMS disrupts predictive language processing. Current Biology, 22(18), R794-R795.
    - Mariën, P., Ackermann, H., Adamaszek, M., Barwood, C. H., Beaton, A., Desmond, J., ... & Ziegler, W. (2014). Consensus paper: language and the cerebellum: an ongoing enigma. The Cerebellum, 13, 386-410.

### Reading log 

As of Friday September 20th, please keep a reading log ([sample](https://docs.google.com/document/d/1lT6hdwARJKxq7Am2mAthvkEFWZDIN2NNu6r6fvuhTrE/edit)) instead of tracking reading in Perusall.  

1. Create a single google doc you will update throughout the semester. 
2. Set share permissions to "anyone with the link"
3. Each week, add a heading that says "Week X: Topic (Date)" (or similar) to your existing document. 
4. Under the week's heading, include the full citation for each paper.
5. Under each paper, include a 250-500 word reflection, including (at least): 
    - a few sentences about the main findings
    - a few sentences of your own critical reflections on the paper
    - and 2 discussion questions you have in mind 
6. Submit the link to your google doc on Canvas by class time each Thursday. 


### Final paper

There are ~~7~~ 6 checkpoints leading up to (and including) the final paper, due on the following Mondays at noon. Extensions of up to 1 week will be granted for any reason. Beyond that, you can turn in any missed checkpoint for half-credit (50%) by the end of the semester.

- [Checkpoint 1: Topic selection due Sep 23](/final_paper/checkpoint-1.qmd)
- [Checkpoint 2: Outline due Oct 7](/final_paper/checkpoint-2.qmd)
- [Checkpoint 3: Peer review 1 due ~~Oct 21~~ Oct 28](/final_paper/checkpoint-3.qmd)
- [Checkpoint 4: Paper draft due Nov 18](/final_paper/checkpoint-5.qmd)
- [Checkpoint 5: Peer review 2 due Dec 5](/final_paper/checkpoint-6.qmd)
- [Checkpoint 6: Final paper due Dec 16](/final_paper/checkpoint-7.qmd)



