project:
  type: website
  output-dir: docs

website:
  title: "Neurolinguistics"
  sidebar:
    style: "docked"
    search: true
    type: "dark"
    contents: 
      - text: Syllabus
        href: index.qmd
      - text: Resources
        href: index.qmd#resources
      - text: Schedule
        href: index.qmd#schedule
      - section: Materials
        href: index.qmd#materials
        contents:
        - text: Readings
          href: index.qmd#readings
        - text: Reading log
          href: index.qmd#reading-log
        - text: Final paper
          href: index.qmd#final-paper
        


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    number-sections: false
  pdf:
    documentclass: scrartcl
    papersize: letter
    toc: false
    number-sections: false
    highlight-style: github


