project:
  type: website
  output-dir: docs

website:
  title: "Neurolinguistics"
  sidebar:
    style: "docked"
    search: true
    type: "dark"
    contents: 
      - text: Syllabus
        href: index.qmd
      - text: Resources
        href: index.qmd#resources
      - text: Readings
        href: index.qmd#readings
      - text: Schedule
        href: index.qmd#schedule

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



