## Schedule 

| Week | Date |  Topic & Discussion Leaders | Due  |
| -  | -- |  ------- | --- | ---- |
| 1 | Aug 29 | [Getting started](getting-started.qmd) <br> Katie (Instructor) | |
| 2 | Sep 5 | [CNS, neurons, and methods](cns-neurons-methods.qmd) <br> Katie (Instructor) |  |
| 3 | Sep 12 | **Perspective** <br> Krakauer et al (2017): Chloe, Dillon, Erica <br> Embick & Poeppel (2015): Esther, Mahir, Sophia |  |
| 4 | Sep 19 | **Networks** <br> [Malik-Moraleda et al 2022](https://canvas.upenn.edu/courses/1809307/assignments/12815591) - Esther, Jo, Na<br>[Fedorenko et al 2024](https://canvas.upenn.edu/courses/1809307/assignments/12815592)- Mahir, Sophia, Jason |   | 
| 5 | Sep 26 | **Phonemes & Syntax** <br> [Fitch & Martins (2014)](assests/readings/fitch-martins-2014.pdf) - Daniel, Dillon, Tali<br>[Makuuchi et al (2009)](assests/readings/makuuchi-et-al-2009.pdf) - Aymeric, Ninjin, Jason | [CP1 Topic selection (due 9/23)](/final_paper/checkpoint-1.qmd)  |
| 6 | Oct 3 | **Fall break (no class)**  | |
| 7 | Oct 10 | **Acquisition I** <br> [Perani et al 2011](https://paperpile.com/shared/sMA8ZGuk1SPKvzFN6USIk6g) - Carey, Leann, Katie<br> [Leroy et al 2011](https://paperpile.com/shared/sbuQsks96Q7y6iBI_lpY3PQ) - Karis, Ninjin<br>[Skeide & Friederici 2016](https://paperpile.com/shared/sc~PeRO27SR6PWvaIkGbl~w) - Tali, Nwai, Na | [CP2 Outline (due 10/7)](/final_paper/checkpoint-2.qmd)  | 
| 8 | Oct 17 | **No class (Katie @ conference)** | | 
| 9 | Oct 24 | **Acquisition II** <br> [Cheng et al 2023](https://paperpile.com/shared/sB1uCvQbrRx21mbYw77OkuQ) - Alyssa, Esther, Jason <br> [Schipke et al 2012](https://paperpile.com/shared/sjO_4tcsDRp~9Q3P_7Ej0xA) - Dillon, Daniel, Aymeric<br> [Petitto et al 2012](https://paperpile.com/shared/sXy5lgxSRTv2Xww1D_z9PzA) - Chloe, Jo, Kamelija  |   | 
| 10 | Oct 31 | **Bilingualism I** <br> Alyssa, Erica, Kamelija, Sophia, Daniel, Aymeric| [CP3 Peer review (due 10/08)](final_paper/checkpoint-3.qmd) |
| 11 | Nov 7 | **Symposium (Zoom):**<br>**Neural Coding in Speech, Language and Cognition**  | |
| 12 | Nov 14 | **Bilingualism II** <br> Carey, Chloe, Leann, Katie, Na, Karis, Jo |  | 
| 13 | Nov 21 | **Sign language** <br> Carey, Leann, Katie, Karis, Tali, Nwai |  [CP4 Paper draft (due 11/18)](/final_paper/checkpoint-5.qmd)   | 
| 14 | Nov 28 |**Thanksgiving break (no class)**    | Peer Review II (Tues) |
| 15 | Dec 5 | **Evolution**  <br>  Alyssa, Erica, Ninjin, Kamelija, Nwai, Mahir | [CP6 Peer review 2 (due 12/5)](/final_paper/checkpoint-6.qmd) |
| 16 | Dec 9 | No class |    |
| 17 |  | [CP7 Final paper (due 12/16)](/final_paper/checkpoint-7.qmd) | 