## Syllabus

**Course Description**: Neurolinguistics is a seminar on language and the brain. For the first few weeks, you will build a foundation of knowledge, first on how brains work (neurons, networks, and anatomy) and later on the methods researchers use to study language in the brain. The remainder of the course will explore the literature on different topics in language and the brain, including various levels of linguistics (phonology, morphology, syntax), acquisition, evolution, signed languages, and more.

**Prerequisites**: This course is open to all graduate students and upper-level undergraduates. No specific background in neuroscience or linguistics is necessary to participate in the course. However, this is an advanced seminar-style course; students looking for a lecture formart will not enjoy this course. 

**Instructor**: [Dr. Katie Schuler (she/her)](https://kathrynschuler.com)

- You can call me **Katie**

**Seminars**: Thursday at 1:45pm in TBD

**Office Hours**: The linguistics department is located on the 3rd floor of 3401-C Walnut street, between Franklin's Table and Modern Eye. 

- Katie Schuler: TBD in 314C

**Requirements**: This is an advanced STEM seminar. Below are the major requiements, but please read the [tips for seminars](tips.qmd) to understand further: 

- **Reading prep**: Each week, you will be responsible for preparing for the discussion by completing the assigned reading. As you read,  you are responsible for asking questions and beginning the discussion of the paper in our reading annotation tool, Perusall. 
- **Discussion leader**: Several times throughout the semester (but not every week), you will serve as discussion leader for a paper with one or two other students. As discussion leader, your group will be responsible for presenting the paper, including summarizing (motivation, research questions, approach, and findings) and leading a discussion of the work. 
- **Final paper**: You will select a paper of interest to you (within the bounds of language and the brain) and write a research analysis of the work (in the form of a nature "News & Views" paper; example [here](https://www.nature.com/articles/d41586-024-02525-z)). There are a few checkpoints leading up to this final paper (including peer review) to help you make progress.

**Grading**:

- 30% Participation in discussion (including reading prep in Perusall)
- 40% Discussion leader 
- 30% Final paper (including several check-points throughout the semester: paper selection, outline, drafts, and peer review)


**Accomodations**: I will support any accommodations arranged through Disability Services via the [Weingarten Center](https://weingartencenter.universitylife.upenn.edu/disability-services/) and to make alternate arrangements when class conflicts with a religious holiday. Please notify me as soon as possible if you require accomodations. 

**Extra credit**: There is no extra credit in the course. However, students can submit any missed reading prep by the end of the semester for half credit (50%).  To ensure fair treatment, all students will receive a 1% "bonus" to their final course grade: 92.54% will become 93.54%.

**Support**: Asking for help is a sign of strength! I hope you’ll reach out to me if you need help (acamdeically or otherwise). I also want you to be aware of Penn’s Academic & Wellness Resources








