## Annotation guidelines

To facilitate discussion in this course, you will be collaboratively annotating the readings with others in your class on Perusall. We will use these annotations to kickstart the discussion and to make the reading process more fun. While you read, you’ll receive rapid answers to your questions from peers, help others resolve their questions (which also helps you learn), and begin discussing the readings together before we meet.

You can start a new annotation thread in Perusall by highlighting text, asking a question, or posting a comment; you can also add a reply or comment to an existing thread. Each thread is like a chat with one or more members of your class. Your goals in annotating each reading assignment are to stimulate discussion by posting good questions or comments and to help others by answering their questions.

Research shows that by annotating thoughtfully, you’ll learn more and get better grades; so here’s what “annotating thoughtfully” means: 

- deeply engage points in the readings
- stimulate discussion
- offer informative questions or comments
- help others by answering their questions or confusions (or sharing that you are also confused by that point). 

To this end Perusall scores your annotations on the basis of quality, timeliness, quantity, and distribution:

Quality
The reading lays the groundwork for more useful activities in class. Therefore it is important that you read the text thoughtfully and attempt to lay the foundation for the work in class. Each of your annotations is assigned one of the following evaluations:
2 = Demonstrates thorough and thoughtful reading AND insightful interpretation of the reading
1 = Demonstrates reading, but no (or only superficial) interpretation of the reading
0 = Does not demonstrate any thoughtful reading or interpretation

Quantity
Perusall computes your overall score using your 6 highest-quality annotations for each assignment, so be sure to write at least this number to ensure the best score. Because we want you to engage in a natural conversation with your classmates through your annotations, your overall score only depends only on these 6 highest-quality annotations. So, as long as you have 6 high quality annotations, a brief response to another student (e.g., answering “Yes” to what is just a yes or no question) won’t hurt your overall score, even though by itself that response is nominally a “0.”

Timeliness
The work done in class depends on you having done the reading in advance, so completing the reading and posting your annotations before the posted deadline is required to receive credit. To encourage discourse, there is always a three-day reply window after each posted deadline during which you can continue to reply, for full credit, to questions posted by others. However, the number of additional points you can earn during the post-deadline reply window is capped at the credit you receive for annotations made on that assignment before the deadline.

Distribution
To lay the foundation for understanding the in-class discussion, you must at least familiarize yourself with each assignment in its entirety. Annotating only part of the text and/or failing to distribute your annotations throughout the document lowers your overall score.

Overall Evaluation
You will receive an overall evaluation for each reading assignment in Perusall based on the criteria above as follows:
3 = exceptional (rarely given)
2 = meets expectations
1 = needs improvement
0 = insufficient
I'll use the Perusall scores when I consider your participation grade.