## Tips for seminars

> These expectations were written by Abby Marsh at Georgetown University and shared here with permission! 

The majority of your grade this semester will reflect your participation in weekly class meetings. Please read the following guidelines about class participation closely.

Taking part in a graduate seminar is quite different from attending an undergraduate seminar in terms of its purpose and what is expected of you. As PhD students, you are training to become academics, and are as a result instructors-in-training. You should think of yourself that way in a graduate seminar. You have the responsibility to both listen and contribute because your knowledge and ideas and conclusions to the class are an essential part of the seminar for all participants. The most stimulating seminars are ones in which students come to class informed about the ideas and really engage with each other about them. Please take this responsibility seriously. 

Specific expectations are that you will: 

- Prepare for class. Do the reading. All of it. But don’t stop there. Annotate your reading. Ask questions of the text in the margins. Always consider what’s at stake in the reading, how the reading informs your understanding of the class themes, other course materials, the methods, the content. How does the reading relate to your own burgeoning research questions?
- Come to class with questions and discussion points. If you are shy about speaking in class, find a peer to chat with about your thoughts before class. Learning to fully participate in intellectual discussions about ideas is an essential part of becoming an academic, so please use this opportunity to practice this skill.
- Do your part to help foster community. When you attend, please close your other windows and remain engaged in the papers and attentive during the class.
- Showcase your intellectual curiosity by engaging with all types of ideas, not just the ones in your designated area of study. Remain open to positions and ideas that contradict your own. Attempt to fully understand them before contradicting them. Phrases such as, “Can I make sure I understand what you’re saying…?” are very useful.
- Direct your comments to the whole class, not just the instructors.
- Use your breadth of knowledge — connect the readings to other readings in your class and other out-of-class readings. Feel free to apply the readings or theme of the day to your own research, but don’t be so focused on utilitarian knowledge that you fail to engage fully with all of the issues at hand.
- Thoughtfully criticize without skewering the reading of the week. This is intellectually lazy. The work must have some redeeming value if the professor has chosen to assign it. Serious critiques of the readings are welcome, but you should attempt to articulate a given reading’s contributions as well as limitations.


## Reading papers 

> The following is an excerpt from a [blog post](https://sarneckalab.blogspot.com/2018/07/writing-workshop-chapter-5.html) (and now book!) by Barbara Sarneka; Read Step 2: Read the Literature for more info 

You need a systematic way of picking the most important points out of an article or chapter without wasting time. Of course, if you genuinely find the reading pleasurable and you want to read every word, and you have the time to do that, don’t let me stop you. But I’m assuming that you just want to get a basic understanding of what’s been done in your field up to now. To avoid confusion let’s give this activity a different verb: Let’s call it surveying. 

How to Survey an Empirical Journal Article

If you are new to an area, expect to spend 30-60 minutes surveying an empirical article. (Don’t worry; after a few years, you will be able to do it in under 10 minutes.) There are times when surveying isn’t appropriate; for example, when I review a manuscript or a grant proposal, I do feel obligated to read every word. But for the purposes of a literature review, surveying is just fine. You can always come back later and read the details if necessary.

1. Read the title.
Make note of any words you don’t understand, or any questions you have.

2. Read the abstract.
The abstract is a summary of the whole paper, and it’s worth taking the time to read carefully, several times over if necessary. Again, make note of any questions you have or words you don’t understand.

3. Scroll through the paper and look at the figures.
Figures that illustrate methods or models should give you a good idea of what the researchers did. Figures that illustrate results should show you what the researchers found, and good ones will show you what the researchers’ hypotheses were. Again, make note of any questions you have.

4. Skim through the rest of the paper for the answers to your questions.
The rest of your reading of this article will be guided by the questions you wrote down in Steps 1-3. With experience, you will be able to find the answers to most questions quickly. Here are some examples of common question types, and where to find the answers.

What does [word] mean? Or, what does [abbreviation] stand for? All technical terms and abbreviations should be defined the first time they are used. But sometimes authors break this rule in the title and abstract, where word counts are limited. So look in the introduction for the definition of your mystery word or abbreviation. If you are reading the paper on a screen, you can save time by using the ‘find’ function to search. If the word or abbreviation is not defined in the paper, shame on those authors. You can decide whether to look it up online (but be careful, because scientific terms can be used very differently across different subfields) or just let it go. Personally, I usually let it go. An author who doesn’t bother to define terms isn’t trying very hard to communicate with me, and is not entitled to more of my valuable time and attention.

What question did the authors set out to answer? You can usually find this information in the last paragraph of the introduction. If the information is not there, the authors haven’t organized their introduction properly. Again, you can choose whether to search further or let it go.

What did they measure, and how did they measure it? This information is in the method section, along with information about who the participants were (for experiments with human subjects) and (hopefully) all the other details you would need in order to replicate the study.

What did the authors find? (Not what they think it means.) How did they analyze their data?  This information is in the results section.

What do the authors think their findings mean? This information is in the discussion.

5. Write a few sentences to a paragraph of notes.
The final step in surveying an article is to write a paragraph or so for your own notes, summarizing the authors’ central claim and the main evidence for it. Also note any details that are particularly relevant to your work. For example, if the study used a design or an analysis that you might use, make a note of it.